// <auto-generated />
using System;
using BlogApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogApp.Migrations
{
    [DbContext(typeof(postDBContext))]
    [Migration("20210306052908_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("BlogApp.Model.Post", b =>
                {
                    b.Property<int>("postId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("postContent");

                    b.Property<string>("postCreatedBy");

                    b.Property<DateTime>("postCreatedDate");

                    b.Property<string>("postSubTitle");

                    b.Property<string>("postTitle");

                    b.HasKey("postId");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
